### ISSUE TITLE
[Question] Eagle Ford Dataset

### ISSUE THREAD

**Issue by mochnaufals** [peidongzhao/SPE-201351-MS#1]
Hello.

I found this research is very interesting. But, I noticed that the dataset that is used for the project is not available in this repo. I have a question if you don't mind, is the Eagle Ford Shale's dataset available for public?

Many thanks,
Naufal Septifiandi.

**Comment by peidongzhao** [comment]
Thank you for your interest. Please read the [README](https://github.com/peidongzhao/SPE-201351-MS/blob/master/README.md) of this repo.
